const validationTypes = {
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    CREATE_PACKAGE:"CREATE_PACKAGE",
    CREATE_ORDER:"CREATE_ORDER",
    CREATE_CONTACT:"CREATE_CONTACT",
    CREATE_ABOUT:"CREATE_ABOUT",

}

module.exports = validationTypes